# Generated by Django 5.2.6 on 2025-10-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_mode",
                    models.CharField(
                        choices=[
                            ("mode1", "ModelA with credit historyl"),
                            ("mode2", "ModelB without credit history"),
                            ("mode3", "ModelA+ModelB"),
                        ],
                        default="mode1",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
