# Generated by Django 5.2.6 on 2025-10-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionconfig",
            name="active_mode",
            field=models.CharField(
                choices=[
                    ("mode1", "ModelA with credit history"),
                    ("mode2", "ModelB without credit history"),
                    ("mode3", "ModelA+ModelB"),
                ],
                default="mode1",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CreditApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "married",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=5
                    ),
                ),
                ("dependents", models.PositiveIntegerField()),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("Graduate", "Graduate"),
                            ("Not Graduate", "Not Graduate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "self_employed",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=5
                    ),
                ),
                (
                    "applicant_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "coapplicant_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("loan_amount_term", models.PositiveIntegerField()),
                ("credit_history", models.FloatField(blank=True, null=True)),
                (
                    "property_area",
                    models.CharField(
                        choices=[
                            ("Urban", "Urban"),
                            ("Semiurban", "Semiurban"),
                            ("Rural", "Rural"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prediction_result", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
