# Generated by Django 5.2.6 on 2025-10-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0002_alter_predictionconfig_active_mode_creditapplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditapplication",
            options={"ordering": ["-created_at"]},
        ),
    ]
