from .analytics_1 import pie_chart_graph
from .analytics_2 import correlation
from .analytics_3 import credit_history_graph
from .analytics_4 import married_graph
from .analytics_5 import property_area_graph
from .analytics_6 import education_graph
from .analytics_7 import dependents_graph
from .analytics_8 import self_employed_graph
from .analytics_9 import correlation_matrix_graph
from .analytics_10 import total_income_graph
from .analytics_11 import chi_square_graph
from .analytics_12 import mutual_score_graph